runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /app/static
  static_dir: static
- url: /.*
  script: app.grouppy.app

libraries:
- name: ssl
  version: latest
- name: PIL
  version: latest
